@baseUrl = http://localhost:3333
###
POST {{baseUrl}}/links
Content-Type: application/json

{
  "originalLink": "https://www.google.com/",
  "shortLink": "google"
}

HTTP/1.1 409  - Conflict
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 144
date: Mon, 15 Sep 2025 23:36:48 GMT
connection: close
###
GET {{baseUrl}}/links

HTTP/1.1 200  - OK
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 494
date: Mon, 15 Sep 2025 23:36:56 GMT
connection: close
###
@id = 01994f2c-d6b5-79eb-914e-c536d3e7dd07

DELETE {{baseUrl}}/links/{{id}}

HTTP/1.1 204  - No Content
access-control-allow-origin: *
date: Mon, 15 Sep 2025 23:35:19 GMT
connection: close