@baseUrl = http://localhost:3333
###
POST {{baseUrl}}/links
Content-Type: application/json

{
  "originalLink": "https://www.docker.com/",
  "shortLink": "docker"
}

HTTP/1.1 201  - Created
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 199
date: Mon, 15 Sep 2025 21:12:22 GMT
connection: close
###
GET {{baseUrl}}/links

HTTP/1.1 200  - OK
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 494
date: Mon, 15 Sep 2025 21:12:24 GMT
connection: close
###
@id = 01994e97-b97b-76a0-9062-6188d5c9ea78

DELETE {{baseUrl}}/links/{{id}}

HTTP/1.1 404  - Not Found
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 192
date: Mon, 15 Sep 2025 21:12:30 GMT
connection: close